### ISSUE TITLE
Add resources for old sessions

### ISSUE THREAD

**Issue by jatin69** [csdu/coding-club-sessions#6]
Hey @rumansaleem 
I think we made several slides, especially towards the end. I did share most of them with you. Let's see if we can find and upload them here.

**Comment by rumansaleem** [comment]
I can recall we have slides from the 'Webservices' session, I'll surely add them here. But, I cant recall if we have any other slides.

**Comment by ankushkhanna1998** [comment]
I do remember slides from the Git and GitHub session. You did share them as well, as a Google Doc link. Here's the [link](https://docs.google.com/presentation/d/123pdxu259GuAvabeMmxrNnqUa_gM7Ag7BVOocep0CoI).
Also, on searching, I found another set of slides from an ad-hoc session. [This](https://jatin69.github.io/tips) one.

**Comment by jatin69** [comment]
Here's the webservices one - [Web services](https://docs.google.com/presentation/d/1gPle0ufR39TDzb7gkCKCMEjMBYfM14U45rWqM2MXHi0/edit?usp=sharing). Add this as well.

**Comment by jatin69** [comment]
Also should we rename the folders to make it more readable?
From `20191106` to `2019-11-06`. This will retain the sorting and make it more readable.

**Comment by jatin69** [comment]
Also, i think the first PTP session was of @rumansaleem on PHP. Let's add the link to that code repo as well.

**Comment by rumansaleem** [comment]
@jatin69, I do remember that I have to add my PTP session. I'd add it here soon. By the time, @yuvrajsab can fix the above mentioned thing.

**Comment by ankushkhanna1998** [comment]
According to `readme`, we have just 4 sessions left for which we have to add resources here. If you guys can share a link or anything for the resources, I can add them here.

**Comment by jatin69** [comment]
@ankushkhanna1998 First 3 sessions were done without a dedicated ppt. 
Ruman's session also didn't have a ppt. It was done via a github repo, commits acting as slides. 
Here's the [github repo used](https://github.com/rumansaleem/php-mvc-demo). We can add this.

**Comment by rumansaleem** [comment]
Here's the link to the slides that we had for PTP session, jatin already shared the source code repo. But, there is nothing much in the slides, just a theoretical overview.

https://slides.com/rumansaleem/web-dev

**Comment by rumansaleem** [comment]
Repo contains the workshop notes organised by each commit. This could be useful, I think we can just copy paste these notes in the section, with link to source code repo and slides.

https://github.com/rumansaleem/php-mvc-demo/blob/master/NOTES.md
