### ISSUE TITLE
Resources for Ad-Hoc sessions

### ISSUE THREAD

**Issue by ankushkhanna1998** [csdu/coding-club-sessions#8]
Hey @jatin69
[This](https://jatin69.github.io/tips) is one ad-hoc session cum talk held on 8th November 2019. Not sure what to do with it.

**Comment by jatin69** [comment]
Let's make a section in readme for Placement sessions. 
The first entry will be of [this web ppt](https://jatin69.github.io/tips/#/). This can't be really converted to pdf without effort. So let's skip the conversion.
The second entry has slides, and can be downloaded from the [my github repo](https://github.com/jatin69/tips). Those can be downloaded and put in as the others.

While you're at it, let's rename the heading `past meetups` to `DUCS Coding Club sessions`.

**Comment by ankushkhanna1998** [comment]
How about naming ```Past Meetups``` as ```Sessions```?
